re structured the project to place testsample.java in the correct directory. it is now in test.java.com.example.teach.test. this was done because i kept getting this error
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: C:\Users\Max Padovan\Documents\COMPUTER SCIENCE\Y2 Sem 1\CAB302\Assignment 1\teach\target\classes
Caused by: java.lang.module.InvalidModuleDescriptorException: testsample.class found in top-level directory (unnamed package not allowed in module)